export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_EVENTS_SUCCESS = 'LOAD_EVENTS_SUCCESS';
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS';

export const LOAD_RULES_SUCCESS = 'LOAD_RULES_SUCCESS';
export const LOAD_SUBRULES_SUCCESS = 'LOAD_SUBRULES_SUCCESS';
export const LOAD_RULESETS_SUCCESS = 'LOAD_RULESETS_SUCCESS';

export const UPDATE_RULE_SUCCESS = 'UPDATE_RULE_SUCCESS';
export const DELETE_RULE_SUCCESS = 'DELETE_RULE_SUCCESS';
export const DELETE_RULE_FROM_EVENT_RULESET_SUCCESS = 'DELETE_RULE_FROM_EVENT_RULESET_SUCCESS';
export const UPDATE_EVENT_RULESET_SUCCESS = 'UPDATE_EVENT_RULESET_SUCCESS';


export const UPDATE_SUBRULES_SUCCESS = 'UPDATE_SUBRULES_SUCCESS';
export const CREATE_SUBRULE_SUCCESS = 'CREATE_SUBRULE_SUCCESS';
export const DELETE_SUBRULE_SUCCESS = 'DELETE_SUBRULE_SUCCESS';
export const DELETE_SUBRULE_FROM_RULE_SUCCESS = 'DELETE_SUBRULE_FROM_RULE_SUCCESS';
export const UPDATE_SUBRULE_SUCCESS = 'UPDATE_SUBRULE_SUCCESS';








