export default {
  events: [],
  rules: [],
  rulesets: [],
  subrules: [],
  ruleTypes: [
    {id: 1, value:"hour_between"},
    {id: 2, value:"complex_param"},
    {id: 3, value:"last_moments"},
    {id: 4, value:"param"},
    {id: 5, value:"old_vs_new"},
    {id: 6, value:"mapping"},
    ],
  momentNames:[
    {id: "uahm", value: "Arriving home"},
    {id: "uawk", value: "Arriving work"},
    {id:"ubft", value:"Breakfast time"},
    {id:"ubrd", value:"User is abroad"},
    {id:"udlp", value:"Experiencing slow performance"},
    {id:"udtm", value:"Dinner time"},
    {id:"ueis", value:"Exercising"},
    {id:"ugts", value:"Going to sleep"},
    {id:"uhme", value:"User in his Home"},
    {id:"uiiv", value:"Book a vacation"},
    {id:"ulfd", value:"Meet new people"},
    {id:"ulhm", value:"Leaving home"},
    {id:"ullt", value:"Lunch time"},
    {id:"ultm", value:"Listen to music"},
    {id:"ulwk", value:"Leaving work"},
    {id:"unat", value:"Order taxi"},
    {id:"undv", value:"Driving"},
    {id:"untr", value:"Using public transportation"},
    {id:"upag", value:"Playing a game"},
    {id:"usol", value:"Shopping"},
    {id:"utap", value:"Taking a photo"},
    {id:"utpb", value:"Wants to play Board games"},
    {id:"uwam", value:"Watching a movie"},
    {id:"uwrk", value:"User in his Work place"},
    {id:"uwte", value:"Ordering food"},
    {id:"uwup", value:"Waking Up"},
    {id: 1, value:"uwup",},
  ],
  operators:[
    {id: 1, value:"="},
    {id: 2, value:"!="},
    {id: 3, value:"in"},
    {id: 4, value:"not in"},
  ],
  valueTypes:[
    {id:1, value:"string"},
    {id:2, value:"bool"},
    {id:3, value:"number"}
  ],

  paramNames:[
    {id:"inapc", type:"complex", valueType:"Instapcat"},
    {id:"reap", type:"complex", valueType:"Resactap"},
    {id:"reapc", type:"complex", valueType:"Resactapcat"},
    {id:"acapc", type:"complex", valueType:"Acapc"},
    {id:"savloc", valueType:"Savloc", type:"complex"},
    {id:"wpul", valueType:"Wpul", type:"complex"},
    {id:"wfng", valueType:"Wfng", type:"complex"},
    {id:"wfmo", valueType:"Wfmo", type:"complex"},
    {id:"bcon", valueType:"Btconn", type:"complex"},
    {id:"wfcn", valueType:"WifiCon", type:"complex"},
    {id:"wfpx", valueType:"WifiProxy", type:"complex"},
    {id:"glod", type:"simple", valueType:"IntParam"},
    {id:"inslun", valueType:"StringToIntParam", type:"simple"},
    {id:"foreapp", valueType:"StringParam", type:"simple"},
    {id:"scron", valueType:"BoolParam", type:"simple"},
    {id:"ulve", valueType:"StringParam", type:"simple"},
    {id:"usloc", valueType:"StringToIntParam", type:"simple"},
    {id:"dos", valueType:"StringParam", type:"simple"},
    {id:"dmod", valueType:"StringParam", type:"simple"},
    {id:"slang", valueType:"StringParam", type:"simple"},
    {id:"ctype", valueType:"StringParam", type:"simple"},
    {id:"mctype", valueType:"StringParam", type:"simple"},
    {id:"mop", valueType:"StringParam", type:"simple"},
    {id:"dname", valueType:"StringParam", type:"simple"},
    {id:"acap", valueType:"StringParam", type:"simple"},
    {id:"geoco", valueType:"StringParam", type:"simple"},
    {id:"geoci", valueType:"StringParam", type:"simple"},
    {id:"esfs", valueType:"IntParam", type:"simple"},
    {id:"ess", valueType:"IntParam", type:"simple"},
    {id:"isfs", valueType:"IntParam", type:"simple"},
    {id:"iss", valueType:"IntParam", type:"simple"},
    {id:"dvolr", valueType:"IntParam", type:"simple"},
    {id:"dvolm", valueType:"IntParam", type:"simple"},
    {id:"dvola", valueType:"IntParam", type:"simple"},
    {id:"dvoln", valueType:"IntParam", type:"simple"},
    {id:"dvolc", valueType:"IntParam", type:"simple"},
    {id:"duse", valueType:"BoolParam", type:"simple"},
    {id:"deflun", valueType:"StringParam", type:"simple"},
    {id:"earcon", valueType:"BoolParam", type:"simple"},
    {id:"dchar", valueType:"BoolParam", type:"simple"},
    {id:"dmstat", valueType:"DmStat", type:"simple"},
    {id:"caact", valueType:"BoolParam", type:"simple"},
    {id:"phad", valueType:"StringToIntParam", type:"simple"},
    {id:"isfp", valueType:"IntParam", type:"simple"},
    {id:"esfp", valueType:"IntParam", type:"simple"},
    {id:"bact", valueType:"BoolParam", type:"simple"},
    {id:"wfct", valueType:"BoolParam", type:"simple"},
    {id:"scror", valueType:"StringParam", type:"simple"},
    {id:"tzone", valueType:"StringParam", type:"simple"},
    // {id:"", valueType:"", type:"simple"},
    // {id:1, value:"earcon"},
    // {id:2, value:"geoco"},
  ],

  mappingNames:[
    {id:1, value:"app2action"},
  ],
  //appToCategory
  appToCategory:[
    {id:10001, value: "Books & Reference"},
    {id:10002 , value:"Game Puzzle"},
    {id:10003, value:"Tools"},
    {id:10004, value:"Entertainment"},
    {id:10005, value:"Personalization"},
    {id:10006, value:"Business"},
    {id:10007, value:"Education"},
    {id:10008, value:"Productivity"},
    {id:10009, value:"Game Strategy"},
    {id:10010, value:"Music & Audio"},
    {id:10011, value:"Maps & Navigation"},
    {id:10012, value:"Lifestyle"},
    {id:10013, value:"Finance"},
    {id:10014, value:"Sports"},
    {id:10015, value:"Game Adventure"},
    {id:10016, value:"Game Educational"},
    {id:10017, value:"Game Racing"},
    {id:10018, value:"Game Casual"},
    {id:10019, value:"Game Board"},
    {id:10020, value:"Game Arcade"},
    {id:10021, value:"Video Players"},
    {id:10022, value:"Communication"},
    {id:10023, value:"Game Card"},
    {id:10024, value:"Social"},
    {id:10025, value:"Travel & Local"},
    {id:10026, value:"Health & Fitness"},
    {id:10027, value:"Family Education"},
    {id:10028, value:"Photography"},
    {id:10029, value:"Medical"},
    {id:10030, value:"Dating"},
    {id:10031, value:"Food & Drink"},
    {id:10032, value:"Game Trivia"},
    {id:10033, value:"News & Magazines"},
    {id:10034, value:"Shopping"},
    {id:10035, value:"Game Casino"},
    {id:10036, value:"House & Home"},
    {id:10037, value:"Libraries & Demo"},
    {id:10038, value:"Weather"},
    {id:10039, value:"Family Braingames"},
    {id:10040, value:"Game Word"},
    {id:10041, value:"Events"},
    {id:10042, value:"Art & Design"},
    {id:10043, value:"Game Simulation"},
    {id:10044, value:"Parenting"},
    {id:10045, value:"Auto & Vehicles"},
    {id:10046, value:"Game Action"},
    {id:10047, value:"Game Sports"},
    {id:10048, value:"Family Pretend"},
    {id:10049, value:"Family Action"},
    {id:10050, value:"Comics"},
    {id:10051, value:"Beauty"},
    {id:10052, value:"Game Music"},
    {id:10053, value:"Game Role Playing"},
    {id:10054, value:"Family Create"},
    {id:10055, value:"Family Musicvideo"},
    {id:10056, value:"Video Players & Editors"},
  ],

  appToAction:[
    {id:"sabh", value:"Book Hotels"},
    {id:"sabv", value:"Book Flights"},
    {id:"saei", value:"Edit an Image"},
    {id:"safpe", value:"Restaurants"},
    {id:"salmu", value:"Listen to Music"},
    {id:"samnp", value:"Meet people"},
    {id:"sand", value:"Navigate"},
    {id:"saof", value:"Order Food"},
    {id:"saop", value:"Optimize Phone"},
    {id:"saot", value:"Order a Taxi"},
    {id:"sapad", value:"Adventure games"},
    {id:"sapag", value:"Arcade games"},
    {id:"sapat", value:"Action games"},
    {id:"sapbg", value:"Board Games"},
    {id:"sapca", value:"Casual games"},
    {id:"sapcg", value:"Casino games"},
    {id:"sapcr", value:"Card games"},
    {id:"sapeg", value:"Educational games"},
    {id:"sapmg", value:"Music games"},
    {id:"sappg", value:"Puzzle games"},
    {id:"saprg", value:"Racing games"},
    {id:"saprp", value:"RPG games"},
    {id:"sapsg", value:"Sports games"},
    {id:"sapsp", value:"Simulation games"},
    {id:"sapst", value:"Strategy games"},
    {id:"sapt", value:"Transportation"},
    {id:"saptg", value:"Trivia games"},
    {id:"sapwg", value:"Words games"},
    {id:"saso", value:"Shopping"},
    {id:"sastr", value:"Exercise"},
    {id:"sawmo", value:"Watch a Movie"},
    {id:"spag", value:"Play a game"},
  ],

  mappingPossibleValues:[
    {id:1, value:1},
    {id:2, value:2}
  ],
  nameToFields:[
    {id: 1, name: "wfcn", field:"connected"},
    {id: 2, name: "wfcn", field:"name"},
  ]
};
